# Node.js


# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: UseNode@1
  inputs:
    version: '8.x'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your powershell commands here.
      
      Write-Host "Hello World Power sheel  ra raghu directory path "$env:System_DefaultWorkingDirectory
      
      # Use the environment variables input below to pass secret variables to this script.
- task: Gulp@1
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'package-solution'
    arguments: '--ship'
    workingDirectory: '$(System.DefaultWorkingDirectory)/MM/$(localpath)'
    enableCodeCoverage: false
- publish: $(System.DefaultWorkingDirectory)/bin/spfx_arti
  artifact: spfx_arti
